/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.actividad3;

/**
 *
 * @author Juan
 */
public class PruebaFigurasFrame extends javax.swing.JFrame {

    /**
     * Creates new form PruebaFigurasFrame
     */
    public PruebaFigurasFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JTabbedPane();
        panelCirculo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radioText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        circuloResult = new javax.swing.JTextPane();
        btnAreaCirculo = new javax.swing.JButton();
        btnPerimetroCirculo = new javax.swing.JButton();
        panelCuadrado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ladoCuadradoText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnAreaCuadrado = new javax.swing.JButton();
        btnPerimetroCuadrado = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        cuadradoResult = new javax.swing.JTextPane();
        panelRectangulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelTrapecio1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        rectanguloResult = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        rectanguloBaseText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        rectanguloAlturaText = new javax.swing.JTextField();
        btnAreaRectangulo = new javax.swing.JButton();
        btnPerimetroRectangulo = new javax.swing.JButton();
        panelTriangulo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        trianguloBaseText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        trianguloAlturaText = new javax.swing.JTextField();
        btnAreaTriangulo = new javax.swing.JButton();
        btnPerimetroTriangulo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        trianguloResult = new javax.swing.JTextPane();
        btnTipoTriangulo = new javax.swing.JButton();
        panelRombo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        diagonal1Text = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        diagonal2Text = new javax.swing.JTextField();
        romboLadoText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnAreaRombo = new javax.swing.JButton();
        btnPerimetroRombo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        romboResult = new javax.swing.JTextPane();
        panelTrapecio = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        trapecioResult = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        baseMenorText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        baseMayorText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        trapecioLado1Text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        trapecioLado2Text = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        trapecioAltura = new javax.swing.JTextField();
        btnAreaTrapecio = new javax.swing.JButton();
        btnPerimetroTrapecio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MesloLGS NF", 0, 24)); // NOI18N
        jLabel1.setText("Circulo");

        jLabel7.setText("Radio");

        circuloResult.setEditable(false);
        jScrollPane1.setViewportView(circuloResult);

        btnAreaCirculo.setText("Area");
        btnAreaCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCirculoActionPerformed(evt);
            }
        });

        btnPerimetroCirculo.setText("Perimetro");
        btnPerimetroCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCirculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCirculoLayout = new javax.swing.GroupLayout(panelCirculo);
        panelCirculo.setLayout(panelCirculoLayout);
        panelCirculoLayout.setHorizontalGroup(
            panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCirculoLayout.createSequentialGroup()
                .addGroup(panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCirculoLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel1))
                    .addGroup(panelCirculoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
                            .addGroup(panelCirculoLayout.createSequentialGroup()
                                .addGroup(panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCirculoLayout.createSequentialGroup()
                                        .addComponent(btnAreaCirculo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnPerimetroCirculo))
                                    .addGroup(panelCirculoLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelCirculoLayout.setVerticalGroup(
            panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCirculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(radioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAreaCirculo)
                    .addComponent(btnPerimetroCirculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel.addTab("Circulo", panelCirculo);

        jLabel2.setFont(new java.awt.Font("MesloLGS NF", 0, 24)); // NOI18N
        jLabel2.setText("Cuadrado");

        jLabel18.setText("Lado");

        btnAreaCuadrado.setText("Area");
        btnAreaCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCuadradoActionPerformed(evt);
            }
        });

        btnPerimetroCuadrado.setText("Perimetro");
        btnPerimetroCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCuadradoActionPerformed(evt);
            }
        });

        cuadradoResult.setEditable(false);
        jScrollPane6.setViewportView(cuadradoResult);

        javax.swing.GroupLayout panelCuadradoLayout = new javax.swing.GroupLayout(panelCuadrado);
        panelCuadrado.setLayout(panelCuadradoLayout);
        panelCuadradoLayout.setHorizontalGroup(
            panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuadradoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ladoCuadradoText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addComponent(jLabel2)
                .addContainerGap(380, Short.MAX_VALUE))
            .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCuadradoLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
                        .addGroup(panelCuadradoLayout.createSequentialGroup()
                            .addComponent(btnAreaCuadrado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPerimetroCuadrado)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(18, 18, 18)))
        );
        panelCuadradoLayout.setVerticalGroup(
            panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuadradoLayout.createSequentialGroup()
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(ladoCuadradoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(395, Short.MAX_VALUE))
            .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCuadradoLayout.createSequentialGroup()
                    .addContainerGap(186, Short.MAX_VALUE)
                    .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAreaCuadrado)
                        .addComponent(btnPerimetroCuadrado))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)))
        );

        panel.addTab("Cuadrado", panelCuadrado);

        jLabel3.setFont(new java.awt.Font("MesloLGS NF", 0, 24)); // NOI18N
        jLabel3.setText("Rectangulo");

        rectanguloResult.setEditable(false);
        jScrollPane5.setViewportView(rectanguloResult);

        jLabel19.setText("Base");

        jLabel20.setText("Altura");

        btnAreaRectangulo.setText("Area");
        btnAreaRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaRectanguloActionPerformed(evt);
            }
        });

        btnPerimetroRectangulo.setText("Perimetro");
        btnPerimetroRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroRectanguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTrapecio1Layout = new javax.swing.GroupLayout(panelTrapecio1);
        panelTrapecio1.setLayout(panelTrapecio1Layout);
        panelTrapecio1Layout.setHorizontalGroup(
            panelTrapecio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrapecio1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelTrapecio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrapecio1Layout.createSequentialGroup()
                        .addGroup(panelTrapecio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelTrapecio1Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rectanguloBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTrapecio1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rectanguloAlturaText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(355, 705, Short.MAX_VALUE))
                    .addGroup(panelTrapecio1Layout.createSequentialGroup()
                        .addGroup(panelTrapecio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTrapecio1Layout.createSequentialGroup()
                                .addComponent(btnAreaRectangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPerimetroRectangulo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panelTrapecio1Layout.setVerticalGroup(
            panelTrapecio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrapecio1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panelTrapecio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(rectanguloBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTrapecio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(rectanguloAlturaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(panelTrapecio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAreaRectangulo)
                    .addComponent(btnPerimetroRectangulo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRectanguloLayout = new javax.swing.GroupLayout(panelRectangulo);
        panelRectangulo.setLayout(panelRectanguloLayout);
        panelRectanguloLayout.setHorizontalGroup(
            panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectanguloLayout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel3)
                .addContainerGap(368, Short.MAX_VALUE))
            .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRectanguloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelTrapecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelRectanguloLayout.setVerticalGroup(
            panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectanguloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(415, Short.MAX_VALUE))
            .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRectanguloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelTrapecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel.addTab("Rectangulo", panelRectangulo);

        jLabel4.setFont(new java.awt.Font("MesloLGS NF", 0, 24)); // NOI18N
        jLabel4.setText("Triangulo");

        jLabel15.setText("Base");

        jLabel17.setText("Altura");

        btnAreaTriangulo.setText("Area");
        btnAreaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaTrianguloActionPerformed(evt);
            }
        });

        btnPerimetroTriangulo.setText("Perimetro");
        btnPerimetroTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroTrianguloActionPerformed(evt);
            }
        });

        trianguloResult.setEditable(false);
        jScrollPane4.setViewportView(trianguloResult);

        btnTipoTriangulo.setText("Tipo de triangulo");
        btnTipoTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTrianguloLayout = new javax.swing.GroupLayout(panelTriangulo);
        panelTriangulo.setLayout(panelTrianguloLayout);
        panelTrianguloLayout.setHorizontalGroup(
            panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrianguloLayout.createSequentialGroup()
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrianguloLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel4))
                    .addGroup(panelTrianguloLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelTrianguloLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(trianguloBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTrianguloLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(trianguloAlturaText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelTrianguloLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnTipoTriangulo)))
                .addContainerGap(365, Short.MAX_VALUE))
            .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTrianguloLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTrianguloLayout.createSequentialGroup()
                            .addComponent(btnAreaTriangulo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPerimetroTriangulo)
                            .addGap(656, 656, 656))
                        .addGroup(panelTrianguloLayout.createSequentialGroup()
                            .addComponent(jScrollPane4)
                            .addGap(12, 12, 12)))))
        );
        panelTrianguloLayout.setVerticalGroup(
            panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(trianguloBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(trianguloAlturaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(btnTipoTriangulo)
                .addContainerGap(237, Short.MAX_VALUE))
            .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTrianguloLayout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAreaTriangulo)
                        .addComponent(btnPerimetroTriangulo))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        panel.addTab("Triangulo", panelTriangulo);

        jLabel5.setFont(new java.awt.Font("MesloLGS NF", 0, 24)); // NOI18N
        jLabel5.setText("Rombo");

        jLabel13.setText("Diagonal 1");

        jLabel14.setText("Diagonal 2");

        jLabel16.setText("Lado");

        btnAreaRombo.setText("Area");
        btnAreaRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaRomboActionPerformed(evt);
            }
        });

        btnPerimetroRombo.setText("Perimetro");
        btnPerimetroRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroRomboActionPerformed(evt);
            }
        });

        romboResult.setEditable(false);
        jScrollPane3.setViewportView(romboResult);

        javax.swing.GroupLayout panelRomboLayout = new javax.swing.GroupLayout(panelRombo);
        panelRombo.setLayout(panelRomboLayout);
        panelRomboLayout.setHorizontalGroup(
            panelRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRomboLayout.createSequentialGroup()
                .addGroup(panelRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRomboLayout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(jLabel5))
                    .addGroup(panelRomboLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRomboLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(diagonal1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRomboLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(diagonal2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRomboLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(romboLadoText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(385, Short.MAX_VALUE))
            .addGroup(panelRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRomboLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(panelRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRomboLayout.createSequentialGroup()
                            .addComponent(btnAreaRombo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPerimetroRombo)
                            .addGap(656, 656, 656))
                        .addGroup(panelRomboLayout.createSequentialGroup()
                            .addComponent(jScrollPane3)
                            .addGap(12, 12, 12)))))
        );
        panelRomboLayout.setVerticalGroup(
            panelRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRomboLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(diagonal1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(diagonal2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(romboLadoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(313, Short.MAX_VALUE))
            .addGroup(panelRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRomboLayout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addGroup(panelRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAreaRombo)
                        .addComponent(btnPerimetroRombo))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        panel.addTab("Rombo", panelRombo);

        jLabel6.setFont(new java.awt.Font("MesloLGS NF", 0, 24)); // NOI18N
        jLabel6.setText("Trapecio");

        trapecioResult.setEditable(false);
        jScrollPane2.setViewportView(trapecioResult);

        jLabel8.setText("Base menor");

        jLabel9.setText("Base mayor");

        jLabel10.setText("Lado 1");

        jLabel11.setText("Lado2");

        jLabel12.setText("Altura");

        btnAreaTrapecio.setText("Area");
        btnAreaTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaTrapecioActionPerformed(evt);
            }
        });

        btnPerimetroTrapecio.setText("Perimetro");
        btnPerimetroTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroTrapecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTrapecioLayout = new javax.swing.GroupLayout(panelTrapecio);
        panelTrapecio.setLayout(panelTrapecioLayout);
        panelTrapecioLayout.setHorizontalGroup(
            panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrapecioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrapecioLayout.createSequentialGroup()
                        .addGroup(panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelTrapecioLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(baseMenorText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTrapecioLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(baseMayorText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTrapecioLayout.createSequentialGroup()
                                .addGroup(panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trapecioAltura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trapecioLado2Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trapecioLado1Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(355, 355, 355))
                    .addGroup(panelTrapecioLayout.createSequentialGroup()
                        .addComponent(btnAreaTrapecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPerimetroTrapecio)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelTrapecioLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelTrapecioLayout.setVerticalGroup(
            panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrapecioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrapecioLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrapecioLayout.createSequentialGroup()
                        .addGroup(panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(baseMenorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(baseMayorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(trapecioLado1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(trapecioLado2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(trapecioAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(panelTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAreaTrapecio)
                    .addComponent(btnPerimetroTrapecio))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panel.addTab("Trapecio", panelTrapecio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerimetroTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroTrapecioActionPerformed
        double baseMayor = Double.parseDouble(baseMenorText.getText());
        double baseMenor = Double.parseDouble(baseMayorText.getText());
        double lado1 = Double.parseDouble(trapecioLado1Text.getText());
        double lado2 = Double.parseDouble(trapecioLado2Text.getText());
        double altura = Double.parseDouble(trapecioAltura.getText());
        
        Trapecio trapecio = new Trapecio(baseMayor, baseMenor, lado1, lado2, altura);
        double perimetro = trapecio.perimetro();
        
        String figureInformation = "Perimetro del trapecio es: " + perimetro;
        trapecioResult.setText(figureInformation);
    }//GEN-LAST:event_btnPerimetroTrapecioActionPerformed

    private void btnAreaTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaTrapecioActionPerformed
        double baseMayor = Double.parseDouble(baseMenorText.getText());
        double baseMenor = Double.parseDouble(baseMayorText.getText());
        double lado1 = Double.parseDouble(trapecioLado1Text.getText());
        double lado2 = Double.parseDouble(trapecioLado2Text.getText());
        double altura = Double.parseDouble(trapecioAltura.getText());
        
        Trapecio trapecio = new Trapecio(baseMayor, baseMenor, lado1, lado2, altura);
        double area = trapecio.area();
        
        String figureInformation = "Area del trapecio es: " + area;
        trapecioResult.setText(figureInformation);
    }//GEN-LAST:event_btnAreaTrapecioActionPerformed

    private void btnAreaRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaRomboActionPerformed
        double diagonal1 = Double.parseDouble(diagonal1Text.getText());
        double diagonal2 = Double.parseDouble(diagonal2Text.getText());
        double lado = Double.parseDouble(romboLadoText.getText());
        
        Rombo rombo = new Rombo(diagonal1, diagonal2, lado);
        double area = rombo.area();
        
        String figureInformation = "Area del rombo es: " + area;
        romboResult.setText(figureInformation);
    }//GEN-LAST:event_btnAreaRomboActionPerformed

    private void btnPerimetroRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroRomboActionPerformed
        double diagonal1 = Double.parseDouble(diagonal1Text.getText());
        double diagonal2 = Double.parseDouble(diagonal2Text.getText());
        double lado = Double.parseDouble(romboLadoText.getText());
        
        Rombo rombo = new Rombo(diagonal1, diagonal2, lado);
        double perimetro = rombo.perimetro();
        
        String figureInformation = "Perimetro del rombo es: " + perimetro;
        romboResult.setText(figureInformation);
    }//GEN-LAST:event_btnPerimetroRomboActionPerformed

    private void btnAreaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaTrianguloActionPerformed
        double base = Double.parseDouble(trianguloBaseText.getText());
        double altura = Double.parseDouble(trianguloAlturaText.getText());
        
        Triangulo triangulo = new Triangulo(base, altura);
        double area = triangulo.area();
        
        String figureInformation = "Area del triangulo es: " + area;
        trianguloResult.setText(figureInformation);
    }//GEN-LAST:event_btnAreaTrianguloActionPerformed

    private void btnPerimetroTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroTrianguloActionPerformed
        double base = Double.parseDouble(trianguloBaseText.getText());
        double altura = Double.parseDouble(trianguloAlturaText.getText());
        
        Triangulo triangulo = new Triangulo(base, altura);
        double perimetro = triangulo.perimetro();
        
        String figureInformation = "Perimetro del triangulo es: " + perimetro;
        trianguloResult.setText(figureInformation);
    }//GEN-LAST:event_btnPerimetroTrianguloActionPerformed

    private void btnAreaRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaRectanguloActionPerformed
        double base = Double.parseDouble(rectanguloBaseText.getText());
        double altura = Double.parseDouble(rectanguloAlturaText.getText());
        
        Rectangulo rectangulo = new Rectangulo(base, altura);
        double area = rectangulo.area();
        
        String figureInformation = "Area del rectangulo es: " + area;
        rectanguloResult.setText(figureInformation);    }//GEN-LAST:event_btnAreaRectanguloActionPerformed

    private void btnPerimetroRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroRectanguloActionPerformed
        double base = Double.parseDouble(rectanguloBaseText.getText());
        double altura = Double.parseDouble(rectanguloAlturaText.getText());
        
        Rectangulo rectangulo = new Rectangulo(base, altura);
        double perimetro = rectangulo.perimetro();
        
        String figureInformation = "Perimetro del rectangulo es: " + perimetro;
        rectanguloResult.setText(figureInformation);
    }//GEN-LAST:event_btnPerimetroRectanguloActionPerformed

    private void btnTipoTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoTrianguloActionPerformed
        double base = Double.parseDouble(trianguloBaseText.getText());
        double altura = Double.parseDouble(trianguloAlturaText.getText());
        
        Triangulo triangulo = new Triangulo(base, altura);
        String tipo = triangulo.tipoTriangulo();
        
        String figureInformation = "Tipo del triangulo es: " + tipo;
        trianguloResult.setText(figureInformation);
    }//GEN-LAST:event_btnTipoTrianguloActionPerformed

    private void btnAreaCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCirculoActionPerformed
        double radio = Double.parseDouble(radioText.getText());
        
        Circulo circulo = new Circulo(radio);
        double area = circulo.area();
        
        String figureInformation = "Area del circulo es: " + area;
        circuloResult.setText(figureInformation);  
    }//GEN-LAST:event_btnAreaCirculoActionPerformed

    private void btnPerimetroCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCirculoActionPerformed
        double radio = Double.parseDouble(radioText.getText());
        
        Circulo circulo = new Circulo(radio);
        double perimetro = circulo.perimetro();
        
        String figureInformation = "Perimetro del circulo es: " + perimetro;
        circuloResult.setText(figureInformation);  
        
    }//GEN-LAST:event_btnPerimetroCirculoActionPerformed

    private void btnAreaCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCuadradoActionPerformed
        double lado = Double.parseDouble(ladoCuadradoText.getText());
        
        Cuadrado cuadrado = new Cuadrado(lado);
        double area = cuadrado.area();
        
        String figureInformation = "Area del cuadrado es: " + area;
        cuadradoResult.setText(figureInformation);  
    }//GEN-LAST:event_btnAreaCuadradoActionPerformed

    private void btnPerimetroCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCuadradoActionPerformed
        double lado = Double.parseDouble(ladoCuadradoText.getText());
        
        Cuadrado cuadrado = new Cuadrado(lado);
        double perimetro = cuadrado.perimetro();
        
        String figureInformation = "Perimetro del cuadrado es: " + perimetro;
        cuadradoResult.setText(figureInformation);
    }//GEN-LAST:event_btnPerimetroCuadradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaFigurasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaFigurasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaFigurasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaFigurasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaFigurasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField baseMayorText;
    private javax.swing.JTextField baseMenorText;
    private javax.swing.JButton btnAreaCirculo;
    private javax.swing.JButton btnAreaCuadrado;
    private javax.swing.JButton btnAreaRectangulo;
    private javax.swing.JButton btnAreaRombo;
    private javax.swing.JButton btnAreaTrapecio;
    private javax.swing.JButton btnAreaTriangulo;
    private javax.swing.JButton btnPerimetroCirculo;
    private javax.swing.JButton btnPerimetroCuadrado;
    private javax.swing.JButton btnPerimetroRectangulo;
    private javax.swing.JButton btnPerimetroRombo;
    private javax.swing.JButton btnPerimetroTrapecio;
    private javax.swing.JButton btnPerimetroTriangulo;
    private javax.swing.JButton btnTipoTriangulo;
    private javax.swing.JTextPane circuloResult;
    private javax.swing.JTextPane cuadradoResult;
    private javax.swing.JTextField diagonal1Text;
    private javax.swing.JTextField diagonal2Text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField ladoCuadradoText;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JPanel panelCirculo;
    private javax.swing.JPanel panelCuadrado;
    private javax.swing.JPanel panelRectangulo;
    private javax.swing.JPanel panelRombo;
    private javax.swing.JPanel panelTrapecio;
    private javax.swing.JPanel panelTrapecio1;
    private javax.swing.JPanel panelTriangulo;
    private javax.swing.JTextField radioText;
    private javax.swing.JTextField rectanguloAlturaText;
    private javax.swing.JTextField rectanguloBaseText;
    private javax.swing.JTextPane rectanguloResult;
    private javax.swing.JTextField romboLadoText;
    private javax.swing.JTextPane romboResult;
    private javax.swing.JTextField trapecioAltura;
    private javax.swing.JTextField trapecioLado1Text;
    private javax.swing.JTextField trapecioLado2Text;
    private javax.swing.JTextPane trapecioResult;
    private javax.swing.JTextField trianguloAlturaText;
    private javax.swing.JTextField trianguloBaseText;
    private javax.swing.JTextPane trianguloResult;
    // End of variables declaration//GEN-END:variables
}
